!#########################################################
! This file is part of OpenAD released under the LGPL.   #
! The full COPYRIGHT notice can be found in the top      #
! level directory of the OpenAD distribution             #
!#########################################################
        subroutine template()
          use OAD_tape
          use OAD_rev

          ! original arguments get inserted before version
          ! and declared here together with all local variables
          ! generated by xaifBooster

!$TEMPLATE_PRAGMA_DECLARATIONS
          type(modeType) :: our_orig_mode
          integer iaddr
          external iaddr
         our_orig_mode = our_rev_mode
         if (our_rev_mode%plain) then
! original function
!$PLACEHOLDER_PRAGMA$ id=1
          end if
          if (our_rev_mode%tape) then
          if(our_rev_mode%topsplit) then
            our_rev_mode%topsplit = .FALSE.
          end if
! taping
!$PLACEHOLDER_PRAGMA$ id=2
          if(our_orig_mode%topsplit) then
            our_rev_mode%tape = .FALSE.
            our_rev_mode%adjoint = .TRUE.
          endif
          end if 
          if (our_rev_mode%adjoint) then
! adjoint
!$PLACEHOLDER_PRAGMA$ id=3
            our_rev_mode = our_orig_mode
          end if 
        end subroutine template
